#  SuperTux
#  Copyright (C) 2021 A. Semphris <semphris@protonmail.com>
#
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU General Public License
#  as published by the Free Software Foundation; either version 3
#  of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.


# This is for platforms that aren't officially supported, but for which buils can be interesting

name: Additional platforms
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request: {}
# TODO the glbinding build
jobs:
  bsd-solaris:

    strategy:
      fail-fast: false
      matrix:
        # TODO: Add the OpenBSD, NetBSD and Solaris VMs whenever possible
        vm_os: [freebsd]
        build_type: [Debug, Release]

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Fetch the whole tree so git describe works
          fetch-depth: 0
          submodules: true
      - name: Build in FreeBSD
        if: ${{ matrix.vm_os == 'freebsd' }}
        env:
          BUILD_TYPE: ${{ matrix.build_type }}
        uses: vmactions/freebsd-vm@v0.1.0
        with:
          envs: 'BUILD_TYPE'
          sync: rsync
          usesh: true
          prepare: |
            pkg install -y pkgconf
            pkg install -y git
            pkg install -y cmake
            pkg install -y sdl2
            pkg install -y sdl2_image
            pkg install -y openal-soft
            pkg install -y glew
            pkg install -y boost-all
            pkg install -y curl
            pkg install -y libogg
            pkg install -y libvorbis
            pkg install -y freetype
            pkg install -y libraqm
          run: |
            mkdir build && cd build
            cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DWARNINGS=ON -DWERROR=ON -DBUILD_TESTS=ON -DCMAKE_INSTALL_MESSAGE=NEVER -DCMAKE_INSTALL_PREFIX=/usr -DINSTALL_SUBDIR_BIN=bin -DINSTALL_SUBDIR_SHARE=share/supertux2
            make -j3 VERBOSE=1
            make install DESTDIR="/tmp/supertux" VERBOSE=1
            ./test_supertux2

  ubports:

    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Fetch the whole tree so git describe works
          fetch-depth: 0
          submodules: true
      - name: Install clickable
        run: |
          sudo apt install docker.io adb git python3 python3-pip
          pip3 install --user --upgrade clickable-ut
          echo PATH=$PATH:~/.local/bin>>~/.bashrc
        # TODO: Build for arm64 and armhf
      - name: Build for amd64
        env:
          BUILD_TYPE: ${{ matrix.build_type }}
        run: clickable --verbose --arch amd64
      - uses: actions/upload-artifact@v2
        with:
          name: "ubports-amd64-${{ matrix.build_type }}-click"
          path: build/x86_64-linux-gnu/app/*.click
          if-no-files-found: ignore